package de.mpg.mpdl.doi.controller;

import java.util.List;

import org.jvnet.hk2.annotations.Service;

import de.mpg.mpdl.doi.exception.DoiAlreadyExistsException;
import de.mpg.mpdl.doi.exception.DoiNotFoundException;
import de.mpg.mpdl.doi.exception.DoiRegisterException;
import de.mpg.mpdl.doi.exception.DoxiException;
import de.mpg.mpdl.doi.exception.MetadataInvalidException;
import de.mpg.mpdl.doi.model.DOI;

public interface DoiControllerInterface {

	/**
	 * returns the URL and metadata for a specific DOI
	 * 
	 * @param doi
	 * @return DOI
	 * @throws DoxiException
	 * @throws DoiNotFoundException
	 */
	public DOI getDOI(String doi) throws DoxiException, DoiNotFoundException;

	/**
	 * returns a list of all already register DOIs for the current user
	 * 
	 * @return List of DOIs
	 * @throws DoxiException
	 */
	public List<DOI> getDOIList() throws DoxiException;

	/**
	 * registers a given DOI with the given metadata and URL
	 * 
	 * @param doi
	 * @param url
	 * @param metadataXml
	 * @return DOI
	 * @throws DoxiException
	 * @throws DoiAlreadyExistsException
	 * @throws MetadataInvalidException
	 * @throws DoiRegisterException
	 */
	
	public DOI createDOI(String doi, String url, String metadataXml)
			throws DoxiException, DoiAlreadyExistsException,
			MetadataInvalidException, DoiRegisterException;

	/**
	 * registers a generated DOI with the given metadata and URL
	 * 
	 * @param url
	 * @param metadataXml
	 * @return DOI
	 * @throws DoxiException
	 * @throws DoiAlreadyExistsException
	 * @throws MetadataInvalidException
	 * @throws DoiRegisterException
	 */
	public DOI createDOIAutoGenerated(String url, String metadataXml)
			throws DoxiException, DoiAlreadyExistsException,
			MetadataInvalidException, DoiRegisterException;

	/**
	 * registers a given DOI suffix with the according prefix and the given
	 * metadata and URL
	 * 
	 * @param suffix
	 * @param url
	 * @param metadataXml
	 * @return DOI
	 * @throws DoxiException
	 * @throws DoiAlreadyExistsException
	 * @throws MetadataInvalidException
	 * @throws DoiRegisterException
	 */
	public DOI createDOIKnownSuffix(String suffix, String url,
			String metadataXml) throws DoxiException,
			DoiAlreadyExistsException, MetadataInvalidException,
			DoiRegisterException;

	/**
	 * updates a given DOI with the given URL an metadata
	 * 
	 * @param doi
	 * @param url
	 * @param metadataXml
	 * @return DOI
	 * @throws DoxiException
	 * @throws DoiNotFoundException
	 * @throws MetadataInvalidException
	 * @throws DoiRegisterException
	 */
	public DOI updateDOI(String doi, String url, String metadataXml)
			throws DoxiException, DoiNotFoundException,
			MetadataInvalidException, DoiRegisterException;

	/**
	 * sets a DOI to inactive (can be undone by updating the DOI again)
	 * 
	 * @param doi
	 * @throws DoxiException
	 */
	public void inactivateDOI(String doi) throws DoxiException;

}