package de.mpg.mdpl.doi.controller;

import javax.ws.rs.core.Response;

import de.mpg.mdpl.doi.exception.DoxiException;
import de.mpg.mdpl.doi.model.DOI;

public interface DoiControllerInterface {

	/**
	 * @return xml
	 * @param doi
	 */
	public DOI getDOI(String doi);

	public String createDOI(String doi, String url, String metadataXml) throws DoxiException;
	
	public String createDOIAutoGenerated(String url, String metadataXml) throws DoxiException;
	
	public String createDOIKnownSuffix(String suffix, String url, String metadataXml) throws DoxiException;

	public String updateDOI(String doi, String url, String metadataXml) throws DoxiException;
	
	public String inactivateDOI(String doi) throws DoxiException;

}